# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-07 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Top_ten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='无名大神', max_length=20, verbose_name='昵称')),
                ('result', models.IntegerField(default=0, verbose_name='分数')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
