# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-07 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game2048', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='top_ten',
            table='top_ten',
        ),
    ]
