# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-07 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game2048', '0002_auto_20191107_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_ten',
            name='result',
            field=models.CharField(default=0, max_length=50, verbose_name='分数'),
        ),
    ]
