# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-21 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game2048', '0004_auto_20191120_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_ten',
            name='result',
            field=models.IntegerField(default=0, verbose_name='分数'),
        ),
    ]
