# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-21 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game2048', '0005_auto_20191121_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='top_ten',
            options={},
        ),
    ]
